language: R
sudo: required
env:
  - _R_CHECK_SYSTEM_CLOCK_=0
r_packages:
  # work around temporary travis + R 3.5 bug
  - devtools
  - covr
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
